export enum InjectionToken {
  TABLE_REPOSITORY = 'TABLE_REPOSITORY',
  TABLE_QUERY = 'TABLE_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  TABLE_FACTORY = 'TABLE_FACTORY'
}
