export enum InjectionToken {
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  MENU_QUERY = 'MENU_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  MENUCATEGORY_REPOSITORY = 'MENUCATEGORY_REPOSITORY',
  IMAGE_REPOSITORY = 'IMAGE_REPOSITORY',
  MENUCATEGORY_QUERY = 'MENUCATEGORY_QUERY',
  MENU_FACTOEY = 'MENU_FACTOEY',
  MENU_CATEGORY_FACTORY = 'MENU_CATEGORY_FACTORY',
  IMAGE_FACTORY = 'IMAGE_FACTORY'
}
