export enum InjectionToken {
  CONTACT_REPOSITORY = 'CONTACT_REPOSITORY',
  CONTACT_QUERY = 'CONTACT_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  CONTACT_FACTORY = 'CONTACT_FACTORY'
}
