export enum InjectionToken {
  SETTING_REPOSITORY = 'SETTING_REPOSITORY',
  SETTING_QUERY = 'SETTING_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  ORDER_GROUP_PAYMENT_QUERY = 'ORDER_GROUP_PAYMENT_QUERY',
  IMAGE_REPOSITORY = 'IMAGE_REPOSITORY',
  LOGO_REPOSITORY = 'LOGO_REPOSITORY',
  LOGO_FACTORY = 'LOGO_FACTORY',
  SETTING_FACTORY = 'SETTING_FACTORY'
}
