export enum InjectionToken {
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  EVENT_GATEWAY = 'EVENT_GATEWAY',
  ADMIN_QUERY = 'ADMIN_QUERY',
  NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY',
  TABLE_QUERY = 'TABLE_QUERY',
  USER_QUERY = 'USER_QUERY',
  MAIN_ORDER_QUERY = 'MAIN_ORDER_QUERY',
  ORDER_QUERY = 'ORDER_QUERY'
}
