export enum InjectionToken {
  NOTICE_REPOSITORY = 'NOTICE_REPOSITORY',
  NOTICE_QUERY = 'NOTICE_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  NOTICE_FACTORY = 'NOTICE_FACTORY'
}
