export enum InjectionToken {
  VERIFICATION_REPOSITORY = 'VERIFICATION_REPOSITORY',
  VERIFICATION_QUERY = 'VERIFICATION_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_QUERY = 'USER_QUERY',
  VERIFICATION_FACTORY = 'VERIFICATION_FACTORY'
}
