export enum InjectionToken {
  PUSH_REPOSITORY = 'PUSH_REPOSITORY',
  PUSH_QUERY = 'MENU_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  TABLE_QUERY = 'TABLE_QUERY',
  PUSH_FACTORY = 'PUSH_FACTORY'
}
