export enum InjectionToken {
  COMMENT_REPOSITORY = 'COMMENT_REPOSITORY',
  COMMENT_QUERY = 'COMMENT_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  COMMENT_FACTORY = 'COMMENT_FACTORY'
}
