export enum InjectionToken {
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_QUERY = 'USER_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  ADMIN_REPOSITORY = 'ADMIN_REPOSITORY',
  ADMIN_QUERY = 'ADMIN_QUERY',
  GROUP_REPOSITORY = 'GROUP_REPOSITORY',
  TABLE_QUERY = 'TABLE_QUERY',
  GROUP_QUERY = 'GROUP_QUERY',
  ADMIN_FACTORY = 'ADMIN_FACTORY',
  USER_FACTORY = 'USER_FACTORY',
  USER_DOMAIN_SERVICE = 'USER_DOMAIN_SERVICE',
  MAIN_ORDER_REPOSITORY = 'MAIN_ORDER_REPOSITORY',
  AMIN_REPOSITORY = 'AMIN_REPOSITORY',
  MAIN_ORDER_FACTORY = 'MAIN_ORDER_FACTORY',
  MARKET_FACTORY = 'MARKET_FACTORY',
  MARKET_REPOSITORY = 'MARKET_REPOSITORY',
  MARKET_QUERY = 'MARKET_QUERY'
}
