export enum InjectionToken {
  GROUP_REPOSITORY = 'GROUP_REPOSITORY',
  GROUP_QUERY = 'GROUP_QUERY',
  INTEGRATION_EVENT_PUBLISHER = 'INTEGRATION_EVENT_PUBLISHER',
  NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY',
  NOTIFICATION_QUERY = 'NOTIFICATION_QUERY',
  ADMIN_QUERY = 'ADMIN_QUERY',
  TABLE_QUERY = 'TABLE_QUERY',
  MENU_QUERY = 'MENU_QUERY',
  ADMIN_REPOSITORY = 'ADMIN_REPOSITORY',
  SETTING_REPOSITORY = 'SETTING_REPOSITORY',
  GROUP_FACTORY = 'GROUP_FACTORY',
  SETTING_FACTORY = 'SETTING_FACTORY',
  GROUP_DOMAIN_SERVICE = 'GROUP_DOMAIN_SERVICE'
}
